### ISSUE TITLE
Do you have any idea about how to handle multiple instrument or orchestration?

### ISSUE THREAD

**Issue by Pikaurd** [Skuldur/Classical-Piano-Composer#23]
Hi Skuldur,
  Thanks for your great job.
  I want to create a tool that take a melody as input (a piano midi for example) and output with many instrument like symphony.
  Maybe we can have two midi file, one of single instrument and another have many instrument. Using the first one as input sequence and second one as output sequence. Perhaps like translation?

  Do you think that works? Any idea will appreciate. Thank you.

**Comment by Skuldur** [comment]
Hi Pikaurd,

I would try using a variation of GAN. Where instead of using a randomized vector as the input of the generator the input would be a vector of the melody.

The input the discriminator would be expecting would be a symphony. This is the rough idea I would start working with.  This problem is heavily reliant on getting good data that might be hard to find, but let me know how it goes. Hope this helps. :)

**Comment by Pikaurd** [comment]
Thanks
